root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"
#  "root" - Air will watch the current folder recursively.
#  "cmd" - the initial command to execute on refresh/build.
#  "full_bin" -  This is what Air will execute on refresh.

[build]
  bin = "./tmp/main"
  cmd = "go build -o ./tmp/main ."
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "bash-scripts"]
  exclude_file = ["__debug_bin"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "dlv --listen=:$DELVE_PORT --headless=true --api-version=2 --accept-multiclient exec $PROJECTDIR/tmp/main"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
