version: '3'

networks:
  auction-api-delve-network:

services:
  auction_api_app_delve:
    container_name: auction-api-app-delve
    build: ./.docker/local/delve
    ports:
      - "8080:8081"
      - "40000:40000"
    volumes:
      - .:/go-workspace/src/auction-api
    env_file:
      - ./.docker/local/delve/.env
    links:
      - auction_api_db_delve
    depends_on:
      - auction_api_db_delve
    networks:
      - auction-api-delve-network
    hostname: test.auction-api-delve.com
    security_opt:
      - "apparmor=unconfined"
    cap_add:
      - "SYS_PTRACE"

  auction_api_db_delve:
    container_name: auction-api-db-delve
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: auction_api_app
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: auction
    networks:
      - auction-api-delve-network