// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repositories

import (
	"github.com/ashishkumar68/auction-api/database"
)

// Injectors from di_container.go:

func NewUserRepository() *UserRepository {
	db := database.NewConnection()
	userRepository := InitUserRepository(db)
	return userRepository
}
