// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repositories

import (
	"gorm.io/gorm"
)

// Injectors from di_container.go:

func NewRepository(conn *gorm.DB) *Repository {
	repo := initRepository(conn)
	return repo
}
