// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"gorm.io/gorm"
)

// Injectors from di_container.go:

func NewUserService(conn *gorm.DB) UserService {
	userService := initUserService(conn)
	return userService
}

func NewItemService(conn *gorm.DB) ItemService {
	itemService := initItemService(conn)
	return itemService
}
